# Default values for go-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.

replicaCount: 2

image:
  repository: moni1999/go-web-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

env:
  - name: ENV
    value: "dev"

nodeSelector: {}
tolerations: []
affinity: {}
